#!/bin/bash

# set some variables
appIconF=$1
toolF=$2

baseDir=$(dirname "$appIconF")
tempGohF="$baseDir"/tempf.goh
appPcxF="$baseDir"/appicon.pcx
toolPcxF="$baseDir"/toolicon.pcx
gohF="$baseDir"/appicon.goh

#
# default color icon, 48x30
#

# convert any modern image format to old-school pcx
# the script "returns" the color index of the magenta background color
# we've added in the process of the conversion that we want to
# mask out for transparency using the "m" option in cvtpcx
identify $appIconF
colormapIdx=$(img2pcx $appIconF $appPcxF | tail -n1)
identify $appPcxF

# call the CVTPCX methusalem
cvtpcx -Sicon -sstandard -anormal -w48 -h30 -m"$colormapIdx" -G -2 -o"$tempGohF" $appPcxF
sed -i 's/\bMoniker\b/Moniker0/g' $tempGohF
cat $tempGohF > $gohF

# cleanup
rm $tempGohF
rm $appPcxF

#
# Tool icon
#

# convert to PCX
identify $toolF
colormapIdx=$(img2pcx $toolF $toolPcxF | tail -n1)
identify $toolPcxF

# call the CVTPCX methusalem
cvtpcx -G -2 -m"$colormapIdx" -Stool -w15 -h15 -o"$tempGohF" $toolPcxF
sed -i 's/\bMoniker\b/Moniker1/g' $tempGohF
cat $tempGohF >> $gohF

# cleanup
rm $tempGohF
rm $toolPcxF