#!/bin/bash

# set some variables
inf=$1
basef="${inf%.*}"
outf="$basef".pcx
gohf="$basef".goh

#convert "$inf" -colors 16 -type Palette text:- | xxd -g3 -c15 > "$gohf"
#convert "$inf" -colors 16 -type Palette -compress none pnm:- > "$gohf"

convert "$inf" -type Palette -colors 16 -unique-colors -compress none pnm:- | awk '{for(i=1;i<=NF;i++) printf("%02X ", $i); print ""}' > "$gohf"
