#!/bin/bash

# set some variables
inf=$1
basef="${inf%.*}"
gohf="$basef".goh
pcxf="temp.pcx"
ppmf="temp.ppm"
giff="palette.gif"

# Colors: 16 => BMF_4BIT or 256 => BMF_8BIT
numColors=16

# CVTPCX file params
style=icon
size=standard
aspect=normal

# -f => uses GrFillBitmap instead of GrDrawBitmap for all monochrome bitmaps
fill=

# -G => output GOH/GOC code instead of ESP/UI
doForGOC=

# -R => Don't put out resource start/end directives; just monikers
res=-R

echo "CREATE CGA/EGA/VGA 16 COLOR PALETTE"
convert xc:"#000000" \
        xc:"#0000AA" \
        xc:"#00AA00" \
        xc:"#00AAAA" \
        xc:"#AA0000" \
        xc:"#AA00AA" \
        xc:"#AA5500" \
        xc:"#AAAAAA" \
        xc:"#555555" \
        xc:"#5555FF" \
        xc:"#55FF55" \
        xc:"#55FFFF" \
        xc:"#FF5555" \
        xc:"#FF55FF" \
        xc:"#FFFF55" \
        xc:"#FFFFFF" \
        +append "$giff"
echo

echo "INPUT FILE"
identify $inf
echo

echo "CONVERT INPUT IMAGE TO OLD-SCHOOL PPM"
# make sure we have a MAGENTA bg (-background '#ff00ff')
# turn pixels with alpha shading either on or off (-channel A -fx "(a>0.5) ? 1.0 : 0")
# remove any transparency layer (-flatten)
# make sure we have a paletted image (-type palette)
# make sure our bitmap is XX colors (-colors 256)
# turn *off* dithering: +dither
# remap all colors to our predefined color map of 16 or 256 colors (-remap)
convert $inf \
        -channel A -fx "(a>0.5) ? 1.0 : 0" \
        -background '#ff00ff' \
        -flatten \
        +dither \
        -remap "$giff" \
        -type palette \
        -colors "$numColors" \
        -compress none \
        "$ppmf"

identify "$ppmf"
echo

echo "CONVERT INPUT IMAGE FROM OLD-SCHOOL PPM TO PCX"
# because old-school PPM can output 4 bit PCX files
# (no modern program can...)
ppmtopcx "$ppmf" -planes=4 > "$pcxf"
identify $pcxf
echo

# make sure we have the correct dimensions
width=`identify -format '%w' "$pcxf"`
height=`identify -format '%h' "$pcxf"`

# find the MAGENTA color value in the Colormap and extract it's index value
# the color index of the magenta background color can be used to
# mask out transparency using the "m" option in cvtpcx
# identify -verbose $outf > "${inf%.*}".txt
colormapIdx=$(identify -verbose "$pcxf" | grep -ioP '\d{0,3}(?=: \(255,0,255\) #FF00FF magenta)' | tail -n1);

echo "CALL THE CVTPCX METHUSALEM"
cvtpcx -S"$style" \
       -s"$size" \
       -a"$aspect" \
       -w"$width" \
       -h"$height" \
       -m"$colormapIdx" \
       $fill \
       $doForGOC \
       $res \
       -2 \
       -o"$gohf" "$pcxf"
echo

echo "CLEANUP"
rm $pcxf
rm $giff
rm $ppmf