#!/bin/sh
##############################################################################
#
# 	Copyright (c) GeoWorks 1991 -- All Rights Reserved
#
# PROJECT:	PC GEOS
# MODULE:	target
# FILE: 	target
# AUTHOR: 	Falk Rehwagen, Oct 26, 2020
#
# REVISION HISTORY:
#	Name	Date		Description
#	----	----		-----------
#	fr	26/10/20	Initial Revision
#
# DESCRIPTION:
#	A script to start the target basebox and optionally
#       connect swat.
#
#	Usage: target [path] [-swat]
#
#	If you give the argument "no", then the things that would be
#	removed will be printed, but not removed.
#
#	$Id: clean,v 1.18 97/02/12 17:08:40 stevey Exp $
#
###############################################################################
if [ "$BASEBOX" = "" ]; then
    BASEBOX=dosbox
fi
OLD_PATH=$PWD
cd ${LOCAL_ROOT}/gbuild/localpc
rm $LOCAL_ROOT/gbuild/localpc/IPX_STAT.TXT
$BASEBOX -conf $ROOT_DIR/bin/basebox.conf -conf $LOCAL_ROOT/basebox_user.conf &
# >/dev/null 2>&1 &
cd $OLD_PATH
