#!/bin/bash
rm ~/gbuild/localpc/ensemble/privdata/token_da.000
rm ~/pcgeos/Appl/Breadbox/BbxBrow/Art/freeicon/appicon.goh
rm ~/pcgeos/Appl/Breadbox/BbxBrow/Art/freeicon/toolicon.goh

img2goh ~/pcgeos/Appl/Breadbox/BbxBrow/Art/freeicon/appicon.png ~/pcgeos/Appl/Breadbox/BbxBrow/Art/freeicon/toolicon.png
cat ~/pcgeos/Appl/Breadbox/BbxBrow/Art/freeicon/appicon.goh > ~/pcgeos/Appl/Breadbox/BbxBrow/Art/appicon.goh
cat ~/pcgeos/Appl/Breadbox/BbxBrow/Art/freeicon/toolicon.goh >> ~/pcgeos/Appl/Breadbox/BbxBrow/Art/appicon.goh