#!/bin/bash
rm ~/gbuild/localpc/ensemble/privdata/TOKEN_DA.000
img2goh ~/pcgeos/Appl/Breadbox/BbxBrow/Art/freeicon/appicon.png
cp ~/pcgeos/Appl/Breadbox/BbxBrow/Art/freeicon/appicon.goh ~/pcgeos/Appl/Breadbox/BbxBrow/Art/appicon.goh