#!/bin/bash
rm ~/gbuild/localpc/ensemble/privdata/token_da.000
rm ~/gbuild/localpc/ensemble/privdata/TOKEN_DA.000

img2goh ~/pcgeos/Appl/Breadbox/BbxBrow/Art/freeicon/appicon1.png ~/pcgeos/Appl/Breadbox/BbxBrow/Art/freeicon/toolicon.png
mv ~/pcgeos/Appl/Breadbox/BbxBrow/Art/freeicon/appicon.goh ~/pcgeos/Appl/Breadbox/BbxBrow/Art/appicon.goh